#
# The MIT License (MIT)
#
# Copyright (c) 2015 Gil Mendes
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

import os

Import('env', 'config')

if config['ARCH'] == 'x86':
    x86_sources = [
        'platform/pc/console.c',
        '../source/drivers/serial/ns16550.c'
    ]
    variants = [
        {
            'arch': 'ia32',
            'ccflags': ['-m32'],
            'asflags': ['-m32'],
            'linkflags': ['-m32'],
            'sources': x86_sources + [
                'arch/ia32/mmu.c',
                '../source/lib/runtime/i386/udivdi3.S',
                '../source/lib/runtime/i386/umoddi3.S',
            ],
        }, {
            'arch': 'amd64',
            'ccflags': ['-m64', '-mcmodel=kernel', '-mno-red-zone'],
            'asflags': ['-m64'],
            'linkflags': ['-m64'],
            'sources': x86_sources + [
                'arch/amd64/mmu.c',
            ],
        },
    ]
else:
    variants = []

main_sources = [
    'console.c',
    'main.c',
    'mm.c',
    '../source/lib/printf.c',
    '../source/lib/string.c',
]

for variant in variants:
    arch = variant['arch']
    ccflags = variant['ccflags'] if 'ccflags' in variant else []
    asflags = variant['asflags'] if 'asflags' in variant else []
    linkflags = variant['linkflags'] if 'linkflags' in variant else []
    variant_sources = variant['sources'] if 'sources' in variant else []

    ldscript = env.LDScript('%s/arch/%s/link.ld' % (arch, arch), 'arch/%s/link.ld.in' % (arch))

    # Override whatever machine-specific flags were used to compile the loader.
    ccflags += [x for x in env['CCFLAGS'] if not x.startswith('-m') and x != '-fpic']
    asflags += [x for x in env['ASFLAGS'] if not x.startswith('-m') and x != '-fpic']

    linkflags += ['-nostdlib', '-Wl,--build-id=none']
    linkflags += ["-Wl,-T,${File('%s/arch/%s/link.ld')}" % (arch, arch)]

    sources = map(File, main_sources + variant_sources)

    # Generate a unique object name per variant for each source file.
    objects = []
    for source in sources:
        path = os.path.splitext(str(source))[0]
        external = str(Dir('../source'))
        if path.startswith(external):
            path = os.path.join(arch, 'external', '%s.o' % (path[len(external) + 1:]))
        else:
            path = os.path.join(arch, '%s.o' % (path))
        objects.append(env.Object(
            path,
            source,
            CCFLAGS = ccflags,
            ASFLAGS = asflags,
            CPPPATH = env['CPPPATH'] + [Dir('include')],
            CPPDEFINES = ['__TEST']))

    target = env.Program('test-%s.elf' % (arch), objects, LINKFLAGS = linkflags)
    Depends(target, ldscript)

    # Generate various information files.
    env.AddPostAction(target, [
        Action('$OBJDUMP -d $TARGET > ${TARGET.base}.lst', None),
        Action('$READELF -aW $TARGET > ${TARGET.base}.rde', None),
        Action('$NM -C $TARGET | sort > ${TARGET.base}.sym', None),
    ])

    Alias('test', File('test-%s.elf' % (arch)))
