[package]
name = "uefi_types"
version = "0.1.0"
description = "Rust UEFI types for Rust lang"
authors = ["Gil Mendes <gil00mendes@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = [ "uefi" ]
readme = "README.md"

[dependencies]
bitflags = "0.9"
