[package]
name = "initium"
version = "0.1.0"
authors = ["Gil Mendes <gil00mendes@gmail.com>"]
publish = false
edition = "2018"

# [[bin]]
# name = 'initium'
# path = "src/lib.rs"

[dependencies]
log = { version = "0.4", default-features = false }

[dependencies.platform]
path = "platform/efi"
