[package]
name = "initium"
version = "0.1.0"
authors = ["Gil Mendes <gil00mendes@gmail.com>"]

[dependencies]

[lib]
crate-type = ["staticlib"]

[profile]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"