[package]
authors = ["Gil Mendes <gil00mendes@gmail.com>"]
name = "platform"
version = "0.1.0"

[dependencies]
uefi_types = { path = "../../uefi_types" }

[profile]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
