[package]
authors = ["Gil Mendes <gil00mendes@gmail.com>"]
name = "platform"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
uefi = { path = "../../libs/uefi-rs" }
uefi-services = { path = "../../libs/uefi-rs/uefi-services" }
# efi = { git = "https://github.com/reynoldsbd/libefi" }
# compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }
# fixedvec = "0.2.3"

[profile]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
