[package]
name = "xtask"
version = "0.0.0"
publish = false

edition.workspace = true

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", default-features = false, features = ["derive", "help", "usage", "std"] }
