[package]
authors = ["Gil Mendes <gil00mendes@gmail.com>"]
name = "arch"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
log = { version = "0.4", default-features = false }
x86_64 = "0.2.7"
