#
# The MIT License (MIT)
#
# Copyright (c) 2014 Gil Mendes (gil0mendes)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

Import('config', 'defaults', 'env')
from util import FeatureSources

sources = FeatureSources(config, [

])

# Set 64-/32-bit-specific flags.
if config['64BIT']:
    env['CCFLAGS'] += ['-m64', '-mcmodel=small', '-mno-red-zone']
    env['ASFLAGS'] += ['-m64']
    env['LINKFLAGS'] += ['-m64']
else:
    env['CCFLAGS'] += ['-m32']
    env['ASFLAGS'] += ['-m32']
    env['LINKFLAGS'] += ['-m32']

    # 32-bit needs some support function from compiler-rt.
    sources += map(lambda x : File('../../lib/runtime/' + x), [
      'i386/udivvdi3.S',
      'i386/umoddi3.S',
      'i386/divdi3.S',
      'i386/moddi3.S'
    ])

# Prevent FPU code generation.
env['CCFLAGS'] += ['-mno-sse', '-mno-mmx', '-mno-sse2', '-mno-3dnow']

# Warn on stack frames that are too large.
env['CCFLAGS'] += ['-Wframe-larger-than=512']

# Default page size may be larger which can result in a large output binary.
env['LINKFLAGS'] += ['-Wl,-z,max-page-size=0x1000', '-Wl,-z,common-page-size=0x1000']

Return('sources')
